#!/usr/bin/env bash

echo "Setting up directory"

rm -rf /home/ubuntu/*

cd /home/admin

mkdir files

for i in {1..15}
do
    dbus-uuidgen >> files/imp_${RANDOM}_file.txt
done

tar -cf imp_files.tar.gz files

for i in {1..10}
do
    dbus-uuidgen >> files/${RANDOM}_file.txt
done

chmod -R 777 files

mv files /home/ubuntu