#!/usr/bin/env bash

if [ ! -f '/home/ubuntu/imp_files.tar.gz' ]; then
    echo "failure"
    exit 1
fi

required_sha=$(sha256sum imp_files.tar.gz)
file_sha=$(sha256sum /home/ubuntu/imp_files.tar.gz | awk '{print $1}')

if [ "${file_sha}" != ${required_sha} ]
then
    echo "failure"
    exit 1
fi

echo "success"