#!/usr/bin/env bash

echo "Setting up directory"

rm -rf /home/ubuntu/*

cd /home/admin

[ ! -f monitord ] && gcc -o monitord monitord.c

cp monitord script.py /home/ubuntu

chown ubuntu:ubuntu /home/ubuntu/script.py

chmod +x /home/ubuntu/monitord