#!/usr/bin/env bash

if [ ! -f '/home/ubuntu/hello.txt' ]; then
    echo "failure"
    exit 1
fi

required_sha="c98c24b677eff44860afea6f493bbaec5bb1c4cbb209c6fc2bbb47f66ff2ad31"
file_sha=$(sha256sum /home/ubuntu/hello.txt | awk '{print $1}')

if [ "${file_sha}" != ${required_sha} ]
then
    echo "failure"
    exit 1
fi

echo "success"