#!/usr/bin/env bash

if [ ! -f '/home/ubuntu/start_server.py' ]; then
    echo "failure"
    exit 1
fi

if ! diff -q "start_servr.py" "/home/ubuntu/start_server.py" > /dev/null;
then
    echo "failure"
    exit 1
fi

echo "success"